# Generated by Django 2.1.5 on 2019-02-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movielist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie_name', models.CharField(max_length=200, null=True)),
                ('thumbnail', models.CharField(max_length=2000, null=True)),
                ('imdb', models.CharField(max_length=20, null=True)),
                ('sypnosis', models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
